### ISSUE TITLE
ModuleNotFoundError: No module named ‘st_on_hover_tabs

### ISSUE THREAD

**Issue by GoofyzHealth** [Socvest/streamlit-on-Hover-tabs#13]
I implemented the side bar from this documentation but in the development stage a problem arose ModuleNotFoundError: No module named ‘st_on_hover_tabs’

I’m using many library like

import pandas as pd
import numpy as np
import calendar
import streamlit as st
import base64
import plotly.express as px
import plotly.graph_objects as go
from datetime import datetime
from streamlit_gsheets import GSheetsConnection
from st_on_hover_tabs import on_hover_tabs
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
st.set_page_config(layout=“wide”)

please help me

**Comment by Socvest** [comment]
Hey, have you installed the packed via pip? If deploying in streamlit cloud, add the package to the requirements.txt file.

**Comment by abhijit-8688** [comment]
Wish I could help

**Comment by GoofyzHealth** [comment]
Akhirnya saya menemukan permasalahannya. Maaf saya tidak menyertakan versi st-on-hover-tabs di requirements.txt. Terima kasih telah membantu

**Comment by GoofyzHealth** [comment]
I finally found the problem. Sorry I didn't include the st-on-hover-tabs version in requirements.txt. Thanks for helping
