### ISSUE TITLE
Don't show tabes when streamlit app open in smartphone

### ISSUE THREAD

**Issue by WhaleFcker** [Socvest/streamlit-on-Hover-tabs#3]
Hi!
First of all, congratulations on the amazing project!

I understand little of css and with a few lines of code I was able to make my design completely customized! Really incredible!

One thing I noticed, when opening the app on my phone, is that the side menu does not appear! Could you help me to resolve this issue?

**Comment by Socvest** [comment]
Hey, glad you like this!

Thanks for bringing this to my attention, I forgot to account for this. Will look into it and get back to you,

**Comment by WhaleFcker** [comment]
Nice! Tks a lot for your attention! I hope to hear from you!

**Comment by Socvest** [comment]
I think I may have sorted it. I replaced the style.css file with a new one. It should account for mobile devices now. Please download and use the new style.css sheet. With mobile devices, the on-hover does not make sense so instead, it will fallback to the default navigation with the button albeit with the original styling and the nav tabs. Let me know if you have any further issues.

**Comment by WhaleFcker** [comment]
Tks a lot man! I tried here with an Iphone and worked, with an Android didn't. But I think that's the Android phone that's very old.

**Comment by Socvest** [comment]
Glad all is well. When I did my tests, I did it on Samsung galaxy phones and on phones screen sizes around 200-300px height/width which seemed to work. Perhaps if you send me the screen sizes I could sort something out?

**Comment by WhaleFcker** [comment]
Mine it's a Samsung Galaxy Note 10+ from 2017.
I searched the screen sizes and didn't find in pixels, I know that the screen is 6.3 inch.
A site says that the resolution is 2280x1080 pixels, don't know if is correct.

**Comment by Socvest** [comment]
Thanks, I will loo into it.

**Comment by WhaleFcker** [comment]
Hello Socvest! I have one more question:

Is it possible that the sidebar instead of dragging the main page, overlaps under it?

**Comment by Socvest** [comment]
Hello [GuiHungaro](https://github.com/GuiHungaro) I did look into it, was a bit more complicated, will look deeper into it this weekend. 

> Hello Socvest! I have one more question:
> 
> Is it possible that the sidebar instead of dragging the main page, overlaps under it?

**Comment by WhaleFcker** [comment]
Tks a lot my friend!! Your work is awesome!

**Comment by Socvest** [comment]
@GuiHungaro Hello, so was able to fix the galaxy note 10+ (can see the sidebar close button now). Could not get it sideways, its a bit complicated and could not adjust the dimensions. Sorry about that. Update the style.css file for the update.

**Comment by WhaleFcker** [comment]
Don't worry! Tks a lot for your time and fixing it to me!
