### ISSUE TITLE
can it support Multi-Page features without show streamlit default multipage side - bar list?

### ISSUE THREAD

**Issue by Vela-zz** [Socvest/streamlit-on-Hover-tabs#6]
can you add some support to multi pages app ?

I store pages follow auth's recommendation, like
and each file in pages have a function render() return streamlit component need to be painted,

```
-hello.py
-pages/
  - pages1.py
  - pages2.py
```

but I found,
1.
if I use some code like 
```
if tabs =='Dashboard':
    pages1.render()

elif tabs == 'Corpus Demo':
    pages2.render()

```
there are no reaction when I click icon

2. suppress streamlit to show default multipage list in the upper part of side-bar

![image](https://user-images.githubusercontent.com/59645193/177452680-a337a6e5-19b5-4ad5-a16d-33ef198ee06b.png)

**Comment by Socvest** [comment]
Hello, Apologies I took a while to respond, have been busy with other stuff. 

1. Not sure how to add support for multipage, but a working solution can be derived from [here](https://discuss.streamlit.io/t/trick-simple-multpage/26121). If this does not work then its probably best to go with the optional_menu_tabs component in the above example. 
2. It seems doing it as per the example above should suppress the extra multipage list in the sidebar. In his [post](https://discuss.streamlit.io/t/trick-simple-multpage/26121?u=rushmore), he highlights how one should place the tabs (not directly under the st.sidebar) which conceals this. 

If the above do not work for you, probably best to use the option_menu component.

Thanks!
