### ISSUE TITLE
Sidebar disappears when I move browser window between monitors or if I resize the browser window

### ISSUE THREAD

**Issue by psyrixen** [Socvest/streamlit-on-Hover-tabs#7]
Hi,

This component is great and I have been making a dashboard for my team. Normally the sidebar works great ,until I resize the browser window or if I move the browser window between multiple monitors. 

Is it supposed to do so? if yes , is there a way I can make the sidebar stay ?

**Comment by Socvest** [comment]
Hello, I deeply apologise for responding late. There have been other comments on this and I will work tonight to rectify these. I had not configured the sidebar css file for other screen sizes. I will update the style.css file to reflect these new realities.

**Comment by Socvest** [comment]
Hello, so I seem to have figured out the issue. When you resize the screen, it seems streamlit has made it such that the sidebar is shifted -300px to the left (off screen) so it won't be visible. I have adjusted the style.css file to reflect these changes. Let me know if it works. :)
